Completed Weather JS App
RyelBanfield/weather-app pull request #1
Opened 2021-06-02 15:53 UTC by RyelBanfield

This PR contained the completed weather app project.

Users can search for a city and select the unit they want for their temperature.
Backgrounds change based on the weather.

2021-06-02 17:12 UTC, SajjadAhmad14 commented on src/index.js
> +  console.log(weatherData);
Please remove `console.log`. It can only be used for debugging.

2021-06-02 17:12 UTC, SajjadAhmad14 commented on src/index.js
> +  console.log(data);
Please remove `console.log`. It can only be used for debugging.

2021-06-02 17:13 UTC, SajjadAhmad14 commented on src/index.js
> +        }
Please remove app logic from DOM-related tasks.

2021-06-02 17:15 UTC, SajjadAhmad14 commented on src/index.js
> +  }
Please remove app logic from DOM-related tasks.

2021-06-02 17:15 UTC, SajjadAhmad14 commented on src/index.js
> +  }
Please remove app logic from DOM-related tasks.

2021-06-02 17:16 UTC, SajjadAhmad14 commented on src/pushToDom.js
> +  }
Please remove app logic from DOM-related tasks.

2021-06-02 17:16 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [x] You have mastered Git flow.
- [x] PR and commit messages are descriptive.
- [x] You have used ES6 syntax everywhere.
## To Improve 🙏
- [x] Please use the updated linter.yml file as linter config from [here](https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml). 
- [x] You have not mentioned the `npm install` command in the `Getting Started` section of your README. The project can not be run locally without running this command. Kindly add it there.
- [x] Toggle functionality from Celsius to Fahrenheit and vice versa is not working. Please make it work. Moreover, when I search for an invalid city name, the app should show a friendly error.
- [ ] async function should handle errors so that it does not crash when an error occurs.
- [x] Please do not use `console.log` because it can slow the app and can make it insecure in the browser.
- [ ] Please do not mix app logic with DOM manipulation tasks.
- [ ] Please see my inline comments for reference.
# Optional
- [ ] It's nice if the app shows the current geolocation of the user when it is first accessed and fetches the weather from that location.
- [ ] Please try to add a new module that only handles weather data fetch. This way your code would be more organized.
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-06-02 20:40 UTC, SajjadAhmad14 commented on README.md
> +# Todo List
The title is wrong. Please fix it!

2021-06-03 16:57 UTC, NtwaliHeritier approved these changes
### **STATUS: APPROVED✔✔✔**

Hello @RyelBanfield 
Great work making the required changes👏👏

You can merge👌👌👍👍

Happy coding💻💻

2021-06-03 16:59 UTC, merged